#! /bin/sh
ECLIPSEDIR="${ECLIPSEDIR:-/home-reseau/laymard/4INFO/prolog/eclipse_basic}"
LD_LIBRARY_PATH="$ECLIPSEDIR/lib/x86_64_linux:$LD_LIBRARY_PATH"
DAVINCIHOME="${DAVINCIHOME:-$ECLIPSEDIR/daVinci/x86_64_linux}"
JRE_HOME="${JRE_HOME:-}"
export ECLIPSEDIR LD_LIBRARY_PATH DAVINCIHOME JRE_HOME
exec "/home-reseau/laymard/4INFO/prolog/eclipse_basic/lib/x86_64_linux/eclipse.exe" "$@"
